### PR TITLE
Fixed case of null `HttpRequestInitializer`

### PR DESCRIPTION
**Pull request by loisaidasam**

### CODE REVIEW

**Comment by hery** [comment]
:+1:

**Comment by benwilber** [comment]
:+1:

**Comment by netpro2k** [comment]
:+1:

**Comment by loisaidasam** [comment]
@wuman any thoughts on this one?

**Comment by loisaidasam** [comment]
Aha just figured out a way to avoid the null issue by setting a new `HttpRequestInitializer` in the builder:

https://github.com/wuman/android-oauth-client/pull/55/commits/1db2a39b6cd0e3ad06627a96a2d500646bb5ad5a

Seems to solve the issue, but it would be better if the library was hardened to protect against builders who don't explicitly set it.

**Comment by sgtcoolguy** [comment]
Fixes #40

**Pull request merged**
